FROM node:24-bookworm-slim AS build

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV CI="true"

RUN corepack enable

WORKDIR /app

COPY . .

RUN pnpm install --frozen-lockfile

ARG NEXT_PUBLIC_APP_ENV
ARG NEXT_PUBLIC_APP_VERSION
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_PILOT_MODE
ARG NEXT_PUBLIC_REGISTRATION_ENABLED
ARG NEXT_PUBLIC_ASSESSMENT_DELIVERY_ENABLED

ENV NEXT_OUTPUT="standalone"
ENV NEXT_PUBLIC_APP_ENV="${NEXT_PUBLIC_APP_ENV}"
ENV NEXT_PUBLIC_APP_VERSION="${NEXT_PUBLIC_APP_VERSION}"
ENV NEXT_PUBLIC_API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL}"
ENV NEXT_PUBLIC_PILOT_MODE="${NEXT_PUBLIC_PILOT_MODE}"
ENV NEXT_PUBLIC_REGISTRATION_ENABLED="${NEXT_PUBLIC_REGISTRATION_ENABLED}"
ENV NEXT_PUBLIC_ASSESSMENT_DELIVERY_ENABLED="${NEXT_PUBLIC_ASSESSMENT_DELIVERY_ENABLED}"

RUN pnpm --filter @edumall/web build

FROM node:24-bookworm-slim AS runtime

ENV NODE_ENV="production"
ENV HOSTNAME="0.0.0.0"
ENV PORT="3000"

WORKDIR /app

COPY --from=build /app/apps/web/.next/standalone ./
COPY --from=build /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=build /app/apps/web/public ./apps/web/public

USER node

CMD ["node", "apps/web/server.js"]
