import { Injectable } from "@nestjs/common";
import PDFDocument from "pdfkit";
import type { AssessmentReleasedReportPdfSource } from "./assessment-report-view.service";

function formatOutputData(value: unknown): string {
  if (value && typeof value === "object" && "band" in value) {
    const band = (value as { band?: unknown }).band;

    if (typeof band === "string") {
      return band;
    }
  }

  return JSON.stringify(value);
}

function formatDate(value: Date | null): string {
  if (!value) {
    return "Not available";
  }

  return new Intl.DateTimeFormat("en-IN", {
    dateStyle: "long",
    timeStyle: "short",
  }).format(value);
}

/**
 * Renders the same student-friendly summary AssessmentReportViewService exposes over the
 * API (construct name + the published interpretation rule's approved output) as a PDF.
 * Never receives or renders raw/standardized scores, percentiles, or norm/interpretation
 * provenance — the source object is already filtered before it reaches this service.
 *
 * This is a provisional report layout (D-007): a plain, legible document, not a
 * validated commercial report design.
 */
@Injectable()
export class AssessmentReportPdfService {
  public render(source: AssessmentReleasedReportPdfSource): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: "A4", margin: 56 });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      this.renderHeader(doc, source);
      this.renderNotice(doc);
      this.renderResults(doc, source);
      this.renderFooter(doc);

      doc.end();
    });
  }

  private renderHeader(doc: PDFKit.PDFDocument, source: AssessmentReleasedReportPdfSource): void {
    doc.fontSize(20).font("Helvetica-Bold").text("The EduMall", { align: "left" });
    doc
      .fontSize(11)
      .font("Helvetica")
      .fillColor("#475569")
      .text("Career Intelligence Platform", { align: "left" });

    doc.moveDown(1.2);
    doc.fillColor("#0f172a").fontSize(16).font("Helvetica-Bold").text(source.assessment.title);
    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#475569")
      .text(
        `${source.assessment.edition} · Form ${source.assessment.form} · ${source.assessment.language.toUpperCase()}`,
      );

    doc.moveDown(0.8);
    doc
      .fontSize(11)
      .fillColor("#0f172a")
      .font("Helvetica-Bold")
      .text(source.candidateName, { continued: false });
    doc.font("Helvetica").fillColor("#475569").text(source.organizationName);
    doc.text(`Released ${formatDate(source.releasedAt)}`);

    doc
      .moveTo(doc.page.margins.left, doc.y + 12)
      .lineTo(doc.page.width - doc.page.margins.right, doc.y + 12)
      .strokeColor("#e2e8f0")
      .stroke();

    doc.moveDown(1.6);
  }

  private renderNotice(doc: PDFKit.PDFDocument): void {
    doc
      .fontSize(9)
      .font("Helvetica-Oblique")
      .fillColor("#64748b")
      .text(
        "This is a provisional report. It uses a version-controlled interpretation library and " +
          "does not constitute a diagnosis, clinical assessment, or a guarantee of career outcomes. " +
          "Discuss these results with a counsellor before making decisions based on them.",
        { align: "left" },
      );

    doc.moveDown(1.2);
  }

  private renderResults(doc: PDFKit.PDFDocument, source: AssessmentReleasedReportPdfSource): void {
    doc.fontSize(13).font("Helvetica-Bold").fillColor("#0f172a").text("Your results");
    doc.moveDown(0.6);

    if (source.results.length === 0) {
      doc
        .fontSize(10)
        .font("Helvetica")
        .fillColor("#475569")
        .text("No results were available for this report.");
      return;
    }

    for (const result of source.results) {
      doc
        .fontSize(11)
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .text(result.constructName ?? "Unnamed area");
      doc
        .fontSize(10)
        .font("Helvetica")
        .fillColor("#334155")
        .text(formatOutputData(result.outputData));
      doc.moveDown(0.6);
    }
  }

  private renderFooter(doc: PDFKit.PDFDocument): void {
    const bottom = doc.page.height - doc.page.margins.bottom + 18;

    doc
      .fontSize(8)
      .font("Helvetica")
      .fillColor("#94a3b8")
      .text(
        "Generated by The EduMall Career Intelligence Platform.",
        doc.page.margins.left,
        bottom,
        {
          width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
          align: "center",
        },
      );
  }
}
